### ISSUE TITLE
Are you looking for contributors?

### ISSUE THREAD

**Issue by gRichardson108** [jeffmdemers/gurps-calculator#9]
Hey, I wanted to reach out and see if you were looking for contributors. I tried sending an email to your admin email at codebyclockwork, but it looks like your email server isn't online anymore.

Since this app is substantially different from the version at gurpscalculator.com, I'm assuming this is a rewrite or port to Angular. I'm learning Angular myself and would be happy to contribute, but I figure it's best if I understand your plans and how the old site factors into them.

**Comment by jeffmdemers** [comment]
Hi!

Yes, please feel free to contribute! It would be most appreciated.

The version here will use much of the old gCalc code as an api server, and all the front end will be ported to angular, with the as much functionality as possible being rewritten for angular (for speed and offline capability purposes). 

Thanks for your interest!

**Comment by jeffmdemers** [comment]
@gRichardson108 come join us in the gurps discord apps channel. I'm Aion on there. We have some other contributors as well.

https://discord.gg/gnkQEap
